[project]
name = "ui"
version = "0.1.0"
description = "Conversation Chat Viewer for WhatsApp Bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg>=3.2.9",
    "psycopg-binary>=3.2.9",
    "pyyaml>=6.0.2",
    "sqlalchemy>=2.0.41",
    "streamlit>=1.46.1",
]
